[build]
  command = "npm run build:bundle"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "src/platforms"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify"
  status = 200
